{% set version = "3.2.0" %}

package:
  name: pastescript
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PasteScript/PasteScript-{{ version }}.tar.gz
  sha256: 9b0f5c0f1c6a510a353fa7c3dc4fdaab9071462d60d24573de76a001fbc172ac

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - paster = paste.script.command:run

requirements:
  host:
    - python
    - pip
    - paste >=3
    - pastedeploy
    - six
  run:
    - python
    - paste >=3
    - pastedeploy
    - six

test:
  imports:
    - paste
    - paste.script
    - paste.script.util
  commands:
    - paster -h

about:
  home: http://pythonpaste.org/script/
  license: MIT
  summary: A pluggable command-line frontend, including commands to setup package file layouts

extra:
  recipe-maintainers:
    - ocefpaf
