{% set version = "3.1.0" %}

package:
  name: pastescript
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PasteScript/PasteScript-2.0.2.tar.gz
  sha256: c03f249805538cc2328741ae8d262a9200ae1c993119b3d9bac4cd422cb476c0

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - paster = paste.script.command:run

requirements:
  host:
    - python
    - pip
    - paste >=3
    - pastedeploy
    - six
  run:
    - python
    - paste >=3
    - pastedeploy
    - six

test:
  imports:
    - paste
    - paste.script
    - paste.script.util
  commands:
    - paster -h

about:
  home: http://pythonpaste.org/script/
  license: MIT
  summary: A pluggable command-line frontend, including commands to setup package file layouts

extra:
  recipe-maintainers:
    - ocefpaf
