{% set version = "2.0.2" %}

package:
  name: pastescript
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PasteScript/PasteScript-2.0.2.tar.gz
  sha256: c03f249805538cc2328741ae8d262a9200ae1c993119b3d9bac4cd422cb476c0

build:
  number: 1
  skip: True  # [py3k]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - paste >=1.3
    - pastedeploy
    - six
  run:
    - python
    - paste >=1.3
    - pastedeploy
    - six

test:
  imports:
    - paste
    - paste.script
    - paste.script.util
  requires:
    - nose >=0.11

about:
  home: http://pythonpaste.org/script/
  license: MIT
  summary: A pluggable command-line frontend, including commands to setup package file layouts

extra:
  recipe-maintainers:
    - ocefpaf
