# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DiE025oW2Q7ZEELUplNdsKWO8hjrk+q2IvND+/+p2bYwGdplj1urnhZuS6IdurpEFbtmVodzv2h2pDfWhogC5FPeGL6nphVOapkY+CV7SAjBK0HXwIaMDTom5376uspiTmZFgkQ7+Cvt8nmWfiexybwPIsMno7vxEMXS2z9qbzD35IFrOd4UZkdwYevC53sDvK9wqaFkLOVqfON2X1tZtqvUk2Nzr0Keb1Atq7iM9rLTEK1KX3RYnr36zJgsQLSSd0DJcdWu52xIVBxOi4PoinNXcdhXm0IgCcA/DIXcPpiNP9fmt1IxC5ecSG2WjWlh0AEkqywIDfL7FxL/cvm0NyO9xg05HMaFK9MUf004q2dQUMtKohixNnmiSQ1kUYCH5vW5MB2Vm1NNVWYtrOiXU9VE19LQDanuH2my2cN0P2+FmQR3G1stlptLmZl1nhsavmhiapv0xvuIKpIgawVeDmZck4nZLB5GWs7Luik/YvutqEixZ5VC9YEud3/uLQPo8Aj8sP1P4zLu9YbMO7AsVW0gsFCr4MHvK0zzoz9x8qn06PDlx1LcKqT24v9XaSY4FyL/ZId9+NcMXHdWDyJRcgNYsefm0BvIcSSRxTfvIf1XjHHWrIgbwQ0DkQvsnqwrMExPtPljJE0810XUBGTghg2YYOXpaW9P1jEODK4jLqE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
