travis:
  secure:
    BINSTAR_TOKEN: hjEZ+aCxe3nuYZv5nrjMXTXh0asoz/zMWlmudkf3lfeWQkUGKc8Sd8yE7lm/qOq0QAqtfQwkWXTJ4htnL8eVJq4MqCxbAAjnvA0w9huQALbThokAZDeZ8z0LjFsE7Q0vcgXqZVqmBdB2Z8btsvPrVSO4ojepLEdsgqpsBqz15e3iNUXL3BY72VA+4Sonl/eL9Xt5Wj6wQKa0P7aZw8BWTdQuxcVjgjLVmfIpANEC65cvK5deMv8rHBh+lavJV8Ltp+xkX/0e4iUkuzc9Lkbp6gW4lomYC3imVqF5OFM/YKjLmUwqMRvrnJn3nc5ap+Nhxsqv8q0xenMLbEJ+SWjgfwINidQo4FjvhM8xnlPT1yvK+C+PiwFM4JFfYsNqOa6AoT4zQytj24yOsjitd1oZji4KqOedbbeKhDGYHcmdimCpqIXIUPc7UWkSWtXRRxGBEhUZnlyv3Y9eLukerehvoclg+iqEm998PGFgkV3At8z9kYoKcVmkdOmtYTuNy9eQESABMSoKIe1Pf/pdSQG9Vlgkhl0bMQRCwgEHsI2IFVGpY6Ie4k8Aee5/y9tXU8l1kmjY9TrAv4lvN9RujrClL5HH8d6uscrAhXKKQNMMYCm3wa1ahiNMQTzP5kfJV3s3V+ygc8sTvTpI6DdSgtV0S10rb2i6S9hWruEfiCGGaIk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
