travis:
  secure:
    BINSTAR_TOKEN: rvZL3NFg+499sRX1AOC1gDIBnRin63+k55mw11eVGaC23FcZhWDqTXy2EnZp4QMx6YZ0TTqXd1pABoqFl8AKULzfOz9srkJyfXocIkadZ7Z1peoK7RuEql6VJE3buKsSLrWiBUPdy01FaeVSNWxZ5Q9T6BtbM20yFNRCf9PZf1yA5kusl7q4+7LYI0EflYQCHZM6JGPgLtmHYNRBU4t3a5yAcoygy5vOxNlHs3IQDCl8Rw/CC/frPUA95dBictQyBT3rJqpumYfVKX9JuZ064k2Jxt4v8yRY1xNaaNngM8GPbxt1xEHgZb/8OY6QVUdKrqZMVJvXlFKih99itX34+naAjtjIvYyumv6xBUIyPpVFIADG/HAWMNIi4mw7oTHu92k8GjmreqrvRRxZgCP0Fi8G0AAmD4ghQAzgrWbtuuEtgn5DqHnMV/SrALXe5QmD1NFEwXIIdOPsBfmCqT/Eqimo8HHnuF82LUX79kbFTan8Za/cWEnVa3Rg/YMfUSXnlf9Z53RliU/imeHq2U7W3YiYHOqlEFSgzuP5ytvcmE6cL6XMUlqAIXF3fd/ASoDqDWxrUkK7loRiutp4TxJC/RIqXfoD0mQpQLGtv58roCSYCUBjP2wJdECHRJehgU+/aHkarHTM5B9qE76QRXxIVmBFcZZSAk9F0T+wA74Ch9A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
