travis:
  secure:
    BINSTAR_TOKEN: DiE025oW2Q7ZEELUplNdsKWO8hjrk+q2IvND+/+p2bYwGdplj1urnhZuS6IdurpEFbtmVodzv2h2pDfWhogC5FPeGL6nphVOapkY+CV7SAjBK0HXwIaMDTom5376uspiTmZFgkQ7+Cvt8nmWfiexybwPIsMno7vxEMXS2z9qbzD35IFrOd4UZkdwYevC53sDvK9wqaFkLOVqfON2X1tZtqvUk2Nzr0Keb1Atq7iM9rLTEK1KX3RYnr36zJgsQLSSd0DJcdWu52xIVBxOi4PoinNXcdhXm0IgCcA/DIXcPpiNP9fmt1IxC5ecSG2WjWlh0AEkqywIDfL7FxL/cvm0NyO9xg05HMaFK9MUf004q2dQUMtKohixNnmiSQ1kUYCH5vW5MB2Vm1NNVWYtrOiXU9VE19LQDanuH2my2cN0P2+FmQR3G1stlptLmZl1nhsavmhiapv0xvuIKpIgawVeDmZck4nZLB5GWs7Luik/YvutqEixZ5VC9YEud3/uLQPo8Aj8sP1P4zLu9YbMO7AsVW0gsFCr4MHvK0zzoz9x8qn06PDlx1LcKqT24v9XaSY4FyL/ZId9+NcMXHdWDyJRcgNYsefm0BvIcSSRxTfvIf1XjHHWrIgbwQ0DkQvsnqwrMExPtPljJE0810XUBGTghg2YYOXpaW9P1jEODK4jLqE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
